version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - go
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
